title: Secure and Innovative Computer Architectures Group
logo: "assets/css/Farhad-New.jpg"
description: Assistant Professor and Entrepreneur 
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
