title: Secure and Innovative Computer Architectures Group
logo: "assets/css/FarhadMerchant-Cropped.jpg"
logo_size: 300
description: Assistant Professor and Entrepreneur 
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
