title: Secure and Innovative Computer Architectures Group
logo: "assets/css/Farhad-New.png"
description: Assistant Professor and Entrepreneur 
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
