title: Secure and Innovative Computer Architectures Group
logo: "assets/css/FarhadMerchant-Cropped.jpg"
stylesheets:
  - /assets/css/custom.css
description: Assistant Professor and Entrepreneur 
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
