title: Secure and Innovative Computer Architectures Group
logo: "assets/css/FarhadMerchant-Cropped.jpg"
img[src*="assets/css/FarhadMerchant-Cropped.jpg"] {
  max-width: 30px;  /* adjust size */
  height: auto;
}
description: Assistant Professor and Entrepreneur 
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
